services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
      PASSWORD: ${PASSWORD} # Login password for the Web UI (Optional)
      DEFAULT_WORKSPACE: "/config/workspace"
    volumes:
      - "./config:/config"
      - "~/homeserver:/config/workspace/homeserver"
    ports:
      - 8443:8443
    restart: unless-stopped
