services:
  filebrowser:
    image: filebrowser/filebrowser
    user: 1000:1000
    ports:
      - 8080:80
    volumes:
      - ~/Public:/srv
      - ./filebrowser.db:/database.db
    restart: unless-stopped
