services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Singapore
      # JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - "./config:/config"
      - "./transcode:/transcode"
      - "~/Public/Shows:/data/shows"
      - "~/Public/Movies:/data/movies"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
